# Generated by Django 5.0 on 2023-12-28 08:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='cpNum',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')]),
        ),
    ]
